### ISSUE TITLE
Version 0.4.0

### ISSUE THREAD

**Issue by DerOliDE** [DerOli82/yadm#1]
Implement new chat commands:
- [x]  **delete**, to remove dimensions
- [x]  **list**, show all yadm dimensons
- [x]  **providers**, to get all selectable world providers
- [x]  **types**, to get all selectable world types
- [x]  **info**, more world infos
- [x]  **reload**, reload patterns from config

**Comment by krakel** [comment]
Und wo kann man das runterladen?
