### ISSUE TITLE
gradle.bat

### ISSUE THREAD

**Issue by krakel** [DerOli82/yadm#8]
Habe mal gradle.bat ausprobiert. 2 Probleme:
1. ich bekomme den gleichen Fehler wie hier https://github.com/ReadyTalk/gradle-readytalk-ci/issues/15
   habe es mit der gleichen Methode behoben, wie dort am Ende beschrieben
2. die Anweisung "%@eval[2+2]" gibt es in Windows nicht. Ich sehe zwar viele ähnliche Batchs im INet, aber keine Beschreibung was da passieren soll. Im Echo on Modus sieht man, das der Batch nicht zur 4NT_args Marke springt. Eval in Windows Batch geht mit: Set /a foo = 4+2. Aber, wenn ich direckt zu 4NT_args springe geht es garnicht. Dann wird CMD_LINE_ARGS wohl falsch gesetzt.
3. set DIRNAME=%~dp0 produziert einen Pfadnamen mit trailing slash. Dadurch hast du weiter hinten bei CLASSPATH eine doppelten Slash. Glaub Windows ist das wohl egal, weiß aber nicht genau. Besser ist 
   set DIRNAME=%~dp0. (mit Punkt am Ende), dadurch c:\path\.\gradle....
4. kann die jars nicht erstellen, da DimensionTemplate.java fehlt. So ein Mist. :)

**Comment by krakel** [comment]
Der Krampf im Batch scheint nur die Unterstützung für JP Software zu sein, eine interaktive Software für Batch.

du brauchst eigentlich nur

```
:init

set CMD_LINE_ARGS=
if "x%~1" == "x" goto execute
set CMD_LINE_ARGS=%*

:execute
```

**Comment by DerOliDE** [comment]
Zu 1-3) Öh kA mit der Gradle Windows Variante habe ich null Erfahrung. ^^ Wenn es damit irgendwelche Probleme gibt, mach einfach einen Pull mit einer Korrektur.

Zu 4) Der aktuelle Stand ist auch nicht lauffähig, daran arbeite ich ja auch gerade, die DimensionTemplate wird es auch nicht mehr geben, da ich sie umbenannt habe. Für eine funktionierende Version musst Du Dir den Branch mit dem Tag 0.4.1 rauspicken:  https://github.com/DerOli82/yadm/tree/0.4.1
